# TODO adjust for your organisation
# hooks and versions should be adjusted to your needs

# Need more hooks? see https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--safe]
        language_version: python{{ cookiecutter.python_version }}

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: flake8
        additional_dependencies: ["flake8-bugbear == 19.3.0"]
        language_version: python{{ cookiecutter.python_version }}
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.2.0
    hooks:
      - id: python-no-log-warn
      - id: rst-backticks

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.12.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        pass_filenames: false
        args: [-lll, --recursive, {{cookiecutter.importable_name}}]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        exclude: 'setup\.py|versioneer\.py'


  - repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
      - id: pydocstyle
        exclude: 'setup\.py|tests|versioneer\.py'
